# Generated by Django 3.0.6 on 2020-05-11 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlstatus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='url_name',
            field=models.CharField(max_length=100),
        ),
    ]
